#ifndef CPEN_PLATFORM_INPUT_HH
#define CPEN_PLATFORM_INPUT_HH

#include <cstdint>

namespace cpen::platform
{
    /// Keyboard keys, identified by physical position on a US layout — the same
    /// model GLFW uses. Pressing the key labelled Z on a QWERTZ keyboard reports
    /// Key::Y; use TextEvent, not KeyEvent, whenever the character matters.
    ///
    /// The enumerator values intentionally mirror GLFW's, which makes the
    /// translation in the callbacks a free static_cast. That is an
    /// implementation detail of the platform layer: static assertions in
    /// window.cc verify the mirror against the real GLFW macros, so a mismatch
    /// is a compile error rather than a silently wrong key.
    enum class Key : std::int16_t
    {
        UNKNOWN = -1,

        SPACE = 32,
        APOSTROPHE = 39,
        COMMA = 44,
        MINUS = 45,
        PERIOD = 46,
        SLASH = 47,

        DIGIT_0 = 48,
        DIGIT_1 = 49,
        DIGIT_2 = 50,
        DIGIT_3 = 51,
        DIGIT_4 = 52,
        DIGIT_5 = 53,
        DIGIT_6 = 54,
        DIGIT_7 = 55,
        DIGIT_8 = 56,
        DIGIT_9 = 57,

        SEMICOLON = 59,
        EQUAL = 61,

        A = 65,
        B = 66,
        C = 67,
        D = 68,
        E = 69,
        F = 70,
        G = 71,
        H = 72,
        I = 73,
        J = 74,
        K = 75,
        L = 76,
        M = 77,
        N = 78,
        O = 79,
        P = 80,
        Q = 81,
        R = 82,
        S = 83,
        T = 84,
        U = 85,
        V = 86,
        W = 87,
        X = 88,
        Y = 89,
        Z = 90,

        LEFT_BRACKET = 91,
        BACKSLASH = 92,
        RIGHT_BRACKET = 93,
        GRAVE_ACCENT = 96,

        ESCAPE = 256,
        ENTER = 257,
        TAB = 258,
        BACKSPACE = 259,
        INSERT = 260,
        DELETE = 261,
        RIGHT = 262,
        LEFT = 263,
        DOWN = 264,
        UP = 265,
        PAGE_UP = 266,
        PAGE_DOWN = 267,
        HOME = 268,
        END = 269,
        CAPS_LOCK = 280,
        SCROLL_LOCK = 281,
        NUM_LOCK = 282,
        PRINT_SCREEN = 283,
        PAUSE = 284,

        F1 = 290,
        F2 = 291,
        F3 = 292,
        F4 = 293,
        F5 = 294,
        F6 = 295,
        F7 = 296,
        F8 = 297,
        F9 = 298,
        F10 = 299,
        F11 = 300,
        F12 = 301,

        KEYPAD_0 = 320,
        KEYPAD_1 = 321,
        KEYPAD_2 = 322,
        KEYPAD_3 = 323,
        KEYPAD_4 = 324,
        KEYPAD_5 = 325,
        KEYPAD_6 = 326,
        KEYPAD_7 = 327,
        KEYPAD_8 = 328,
        KEYPAD_9 = 329,
        KEYPAD_DECIMAL = 330,
        KEYPAD_DIVIDE = 331,
        KEYPAD_MULTIPLY = 332,
        KEYPAD_SUBTRACT = 333,
        KEYPAD_ADD = 334,
        KEYPAD_ENTER = 335,
        KEYPAD_EQUAL = 336,

        LEFT_SHIFT = 340,
        LEFT_CONTROL = 341,
        LEFT_ALT = 342,
        LEFT_SUPER = 343,
        RIGHT_SHIFT = 344,
        RIGHT_CONTROL = 345,
        RIGHT_ALT = 346,
        RIGHT_SUPER = 347,
        MENU = 348,
    };

    /// Mouse buttons. Values mirror GLFW's, verified by static assertion.
    enum class MouseButton : std::uint8_t
    {
        LEFT = 0,
        RIGHT = 1,
        MIDDLE = 2,
        BUTTON_4 = 3,
        BUTTON_5 = 4,
        BUTTON_6 = 5,
        BUTTON_7 = 6,
        BUTTON_8 = 7,
    };

    /// What happened to a key or button. REPEAT is generated by the operating
    /// system's auto-repeat while a key is held; it is what text-entry and
    /// menu-navigation want, and what a "was just pressed" check must exclude.
    enum class InputAction : std::uint8_t
    {
        RELEASE = 0,
        PRESS = 1,
        REPEAT = 2,
    };

    /// Modifier keys held at the moment of an input event.
    ///
    /// Deliberately a struct of flags rather than a bitmask enum: reading
    /// `event.modifiers.control` needs no mask constants, no bitwise operators
    /// and no lookup of what bit means what.
    struct Modifiers
    {
        bool shift = false;
        bool control = false;
        bool alt = false;
        bool super = false;
        bool caps_lock = false;
        bool num_lock = false;
    };
}

#endif //CPEN_PLATFORM_INPUT_HH
